### ISSUE TITLE
No data to display

### ISSUE THREAD

**Issue by codyliou** [efigence/redmine_issue_statistics#1]
Always show No data to display ,Setting wrong?
![image](https://cloud.githubusercontent.com/assets/5194005/4282812/e29ec1fa-3d62-11e4-8526-2e068bac02a4.png)

![image](https://cloud.githubusercontent.com/assets/5194005/4282852/92937e7a-3d63-11e4-979b-63aefbbbd600.png)

![image](https://cloud.githubusercontent.com/assets/5194005/4282854/98148eb6-3d63-11e4-8c22-89b0565b9c64.png)

---

Environment:
  Redmine version                2.5.2.stable
  Ruby version                   2.0.0-p247 (2013-06-27) [i386-mingw32]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.3
  Mercurial                      3.0.1
  Git                            1.8.4
  Filesystem  
Redmine plugins:
  espeo_additional_project_settings 1.0.0
  espeo_budget                   1.0.0
  espeo_file_image_custom_field  1.0.0
  quick_edit                     0.0.6
  redmine_angular_ui             0.0.1
  redmine_base_deface            0.0.1
  redmine_boards_watchers        0.2.7
  redmine_centosadmin_rating     0.1.0
  redmine_custom_field_aggregator 0.0.1
  redmine_issue_statistics       0.0.1
  resource                       0.0.1
  unread_issues                  0.0.1

**Comment by rlisowski** [comment]
Did you run calculations?  `RedmineIssueStatistics::CalculateStatistic.new.calculate`
Plugin does not determines way to do it. You can run it in console, or create daily cron work. It's up to you.

See [documentation](https://github.com/efigence/redmine_issue_statistics/blob/master/Documentation.md).

**Comment by rlisowski** [comment]
We add rake `RAILS_ENV=production bundle exec rake issue_statistics:calculate` to make it easy.
You should do it every day, eg with cron.
