### ISSUE TITLE
Usage Question---Allowed groups,Number of returns issue,Return issue,calculating

### ISSUE THREAD

**Issue by fengyedou** [efigence/redmine_issue_statistics#4]
About Usage Questions

1.Allowed groups---I saw from the configuration page of this plug-in, all groups are listed, do I need to choose or no need, listed groups are allowed to see the data.
2.Calculating is for all projects, right? But for each project member, only their project data can be seen?
3.Number of returns issue-what is the number meaning, now it is 1.
Numer of statistics on page-the same question, now it is 1.
4.Return issue-means according to the defined issue flow, it is ubnormal, e.g. closed issue is opened, such like that,right?
5.The calculating time is long for all projects, is there way of calculating based on selected projects?If I want to calculate one project, then can choose one project, if I want to calculate all projects, then can choose all projects.

**Comment by swiatkiewicz** [comment]
@fengyedou :
Ad. 1 - If you want that groups can see their stats you should select this group/groups in configuration.
Ad. 2 - Yes. Yes, this calculate issue for member in current project.
Ad. 3 - 'returned issue' - flow is : ex. if user change issue status on resolved and change assigned to tester, but tester say 'this issue isn't resolved' and re-assigned back to this user, then number of returns for this user and issue is 1. Number of returns - flow repeated few times ex. 2.
Ad. 4 - Yes, see  Ad. 3 .
Ad. 5 - No, it's calculate all projects. I'll think about this idea, maybe it can be implemented. 

Please see documentation of usage, there is 'cofiguration' paragraph.

**Comment by fengyedou** [comment]
@swiatkiewicz

Ad. 1 - If you want that groups can see their stats you should select this group/groups in configuration.
--------------I want each group only can see their group's statistics, but I donot know how to make it well, I have checked with this link: https://github.com/efigence/redmine_issue_statistics/blob/master/Documentation.md
and I tested I need to select all groups to make sure each group member to see the statistics, but if all groups are selected, all users can search other group's statistics graph.

Ad. 3 - 'returned issue' - flow is : ex. if user change issue status on resolved and change assigned to tester, but tester say 'this issue isn't resolved' and re-assigned back to this user, then number of returns for this user and issue is 1. Number of returns - flow repeated few times ex. 2.---------------So it can be limit the returned flow times, right? if I set it 2, that means, only twice can be returned?

Ad. 5 - No, it's calculate all projects. I'll think about this idea, maybe it can be implemented. ----------That will be great! Can you think about the chance to add this feature #3 and #2?

**Comment by fengyedou** [comment]
@swiatkiewicz 
Another  settings I want to get the real meaning is below:

Number of commentes in issue (ex. if you set 2, then stats will be looking for only this issues where is more then 2 comments)------------the default is 5, what does it use for? I am confused about this setting.

**Comment by swiatkiewicz** [comment]
This means that we are looking for issues where it's propably something wrong ex. 'description' is incomprehensible and developer or someone else ask or write a lot of comments to try understood...
