### ISSUE TITLE
Bug---404 The page you were trying to access doesn't exist or has been removed(When clicking to the return graph data)

### ISSUE THREAD

**Issue by fengyedou** [efigence/redmine_issue_statistics#7]
Env.: Redmine 2.3.2

Error:

404
The page you were trying to access doesn't exist or has been removed.

Test Scene:

I configured issue status from: resolved, issue status to: new and in the progress for return flow in the plug-in setting.

And I searched for several projects, there is return graph to show how many issues have return flow. But I click to the data in the return graph, there is 404 error, I checked other graph, total..open...closed, when I click to the data, issue lists will show.

Error log in prodcution.log is
//////////////////////////////////////////////////
Started GET "/redmine//issue_statistics/returned_issues/23/Project/all/" for xxxx at 2014-11-13 13:50:27 +0800
Processing by IssueStatisticsController#returned_issues as HTML
  Parameters: {"statisticable_id"=>"23", "statisticable_type"=>"Project", "period"=>"all"}
  Current user: xxx (id=1)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.0ms)
  Rendered plugins/redmine_create_wiki_page/app/views/create_wiki_page/_init_create_wiki_page.erb (0.0ms)
  Rendered inline template (0.0ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_head.html.erb (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.0ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.0ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (0.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (0.0ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_body_bottom.html.erb (31.2ms)
  Rendered plugins/redmine_banner/app/views/banner/_after_top_menu.html.erb (31.2ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.0ms)
  Rendered plugins/redmine_user_mentions/app/views/hooks/redmine_user_mentions/_edit_mentionable.html.erb (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (0.0ms)
Completed 404 Not Found in 281ms (Views: 265.2ms | ActiveRecord: 15.6ms)
Started GET "/redmine/boards/59/topics/224" for xxx at 2014-11-13 13:50:29 +0800

**Comment by fengyedou** [comment]
There is such key words:

Missing template, responding with 404

Completed 404 Not Found

**Comment by swiatkiewicz** [comment]
@fengyedou :
Thanks, there was an mistake in controller, see last commit diff.

**Comment by fengyedou** [comment]
Yes, Great! It fixed.!
